In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim


1

In [6]:
arr.shape

(4,)

In [7]:
arr.dtype

dtype('int32')

In [9]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [14]:
arr3 = np.array([[1,2,3],[5,6,7],[8,9,10],[11,12,13],[14,15,16],[17,18,19]])

In [17]:
arr3 = np.array([[1,2,3],[5,6,7],[8,9,10],[11,12,13],[14,15,16],[17,18,19]])
print(arr3)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr3 = np.arange(4,20)
print(arr3)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
arr3.reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
arr3.reshape(2,8)

array([[ 4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [25]:
arr3.reshape(2,4,2)

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [26]:
arr = np.arange(16)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
arr[5]

5

In [31]:
arr[:5]

array([0, 1, 2, 3, 4])

In [32]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
arr[[2,4,6]]

array([2, 4, 6])

In [36]:
arr2 = np.array([[1,2,-9,8],[5,7,-3,-8],[12,14,-88,45]])

In [38]:
arr2

array([[  1,   2,  -9,   8],
       [  5,   7,  -3,  -8],
       [ 12,  14, -88,  45]])

In [39]:
arr2[2]

array([ 12,  14, -88,  45])

In [40]:
arr2[:,1]

array([ 2,  7, 14])

In [41]:
arr2[[1,2],[2]]

array([ -3, -88])

In [45]:
arr3 = np.arange(10,82,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [46]:
len(arr3)

36

In [47]:
arr3 = np.arange(10,82,2).reshape(6,6)

In [48]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [49]:
arr3[:,[0,3]]

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [50]:
arr3[:2,:]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [51]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [52]:
arr3.sum()

1620

In [54]:
arr3.mean()

45.0

In [58]:
arr3.mean(0) #col wise mean

array([40., 42., 44., 46., 48., 50.])

In [57]:
arr3.mean(1) #row wise mean

array([15., 27., 39., 51., 63., 75.])

In [59]:
arr = np.arange(1,17).reshape(4,4)

In [60]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [61]:
arr + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [62]:
arr * 5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60],
       [65, 70, 75, 80]])

In [63]:
arr[3]

array([13, 14, 15, 16])

In [64]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
arr[2] = -9


In [66]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-9, -9, -9, -9],
       [13, 14, 15, 16]])

In [68]:
np.sqrt(arr) #no squre root for negative number

C:\Users\ajiakshay\AppData\Local\Temp\ipykernel_13220\687806216.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr) #no squre root for negative number


array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [       nan,        nan,        nan,        nan],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [70]:
# special array

In [71]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [72]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [74]:
np.eye(4,4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(2,4)
print(A)
print(B)
A.dot(B)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

NameError: name 'B' is not defined

In [80]:
A.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [81]:
A.dot(B)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [94]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
b = np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
np.vstack((a,b)) #vertical stacking

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [96]:
np.hstack([a,b]) #horizontal stack

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [97]:
np.concatenate([a,b])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
np.concatenate([a,b], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [99]:
a.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
b.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
# Random number generation

In [102]:
np.random.rand(5)

array([0.98763099, 0.76015284, 0.36420907, 0.72830932, 0.55521949])

In [103]:
np.random.randint(5)

3

In [106]:
np.random.randint(5,20)

14

In [108]:
arr = np.random.randint(0,50,6)
arr

array([21, 11,  2,  1, 37, 30])

In [109]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [110]:
np.random.shuffle(arr)

In [111]:
arr

array([3, 4, 1, 5, 2])

In [116]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 

newarr = arr.reshape(2, 3, 2)#outerdimension, array, element

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [120]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4)

print(newarr) 

[[1 2 3 4]
 [5 6 7 8]]


In [114]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
