In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [5]:
arr.shape

(4,)

In [6]:
arr.dtype

dtype('int64')

In [8]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [12]:
arr3

([[1, 2, 3], [5, 6, 7]],
 [[8, 9, 10], [11, 12, 13]],
 [[17, 18, 19], [20, 21, 22]])

In [15]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr3 = np.arange(4,20)
print(arr3)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
arr3.shape

(16,)

In [20]:
arr3.reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
arr3.reshape(2,8)

array([[ 4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
arr3.reshape(2,4,2)

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

Array Slicing

In [23]:
arr = np.arange(16)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [26]:
arr[5]

5

In [28]:
arr[:5]

array([0, 1, 2, 3, 4])

In [29]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
arr[[2,4,6]]

array([2, 4, 6])

In [32]:
arr=np.array([4,1,9,3,7,3,2])

In [33]:
arr[[2,4,6]]

array([9, 7, 2])

In [34]:
arr2 = np.array([[1,2,-9,8],[5,7,-3,-8],[12,14,-88,45]])

In [35]:
arr2

array([[  1,   2,  -9,   8],
       [  5,   7,  -3,  -8],
       [ 12,  14, -88,  45]])

In [36]:
arr2[2]

array([ 12,  14, -88,  45])

In [37]:
arr2[:,1]

array([ 2,  7, 14])

In [39]:
arr2[[1,2],[2]]

array([ -3, -88])

In [40]:
arr3=np.arange(10,82,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [41]:
len(arr3)

36

In [42]:
arr3=np.arange(10,82,2).reshape(6,6)

In [43]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [44]:
arr3[:,[0,3]]     #All rows, 0th and 3rd column

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [45]:
arr3[:2,:]    #Rows:0-2   Columns:All

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

Numerical Operations

In [46]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [47]:
arr3.sum()

1620

In [49]:
arr3.mean()

45.0

In [50]:
arr3.mean(0)

array([40., 42., 44., 46., 48., 50.])

In [51]:
arr3.mean(1)

array([15., 27., 39., 51., 63., 75.])

In [53]:
arr = np.arange(1,17).reshape(4,4)

In [54]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
arr + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [56]:
arr * 5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60],
       [65, 70, 75, 80]])

In [58]:
arr[3]

array([13, 14, 15, 16])

In [59]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
arr[2] = -9

In [61]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-9, -9, -9, -9],
       [13, 14, 15, 16]])

In [62]:
np.sqrt(arr)

<ipython-input-62-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [       nan,        nan,        nan,        nan],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

Special Arrays

In [63]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [64]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [65]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(4,2)
print(A)

[[0 1 2 3]
 [4 5 6 7]]


In [69]:
A.dot(B)

array([[28, 34],
       [76, 98]])

In [70]:
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [71]:
A.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

Stacking of Arrays

In [76]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
b = np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
np.vstack([a,b])  #vertical stacking

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
np.hstack([a,b])  #horizontal stacking

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [84]:
np.concatenate((a,b))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
np.concatenate((a,b),axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

Flatten

In [86]:
a.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
b.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Random numbers

In [88]:
np.random.rand(5)

array([0.93112531, 0.12208945, 0.26068386, 0.99511222, 0.03664467])

In [94]:
np.random.randint(5)

3

In [99]:
np.random.randint(5,20)

14

In [103]:
arr = np.random.randint(0,50,6)

In [104]:
arr

array([35,  3, 20, 33, 20, 44])

In [105]:
arr = np.arange(1,6)

In [106]:
arr

array([1, 2, 3, 4, 5])

In [107]:
np.random.shuffle(arr)

In [108]:
arr

array([3, 4, 1, 2, 5])