In [117]:
import numpy as np

In [16]:
integers = np.array([10,20,30,40,50], dtype = np.int64)
integers

array([10, 20, 30, 40, 50], dtype=int64)

In [5]:
integers[0] = 20

In [6]:
integers

array([20, 20, 30, 40, 50])

In [17]:
integers.dtype

dtype('int64')

In [15]:
smallintegers = np.array(integers,dtype = np.int8)
smallintegers

array([20, 20, 30, 40, 50], dtype=int8)

In [19]:
integers.nbytes

40

In [20]:
smallintegers.nbytes

5

In [21]:
floats = np.array([1.2,2.3,3.4,5.1,8.3])
floats

array([1.2, 2.3, 3.4, 5.1, 8.3])

In [22]:
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [23]:
floats.dtype

dtype('float64')

In [25]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
nums[0,0]

1

In [27]:
nums[1,4]

10

In [28]:
nums.ndim

2

In [29]:
multi_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [30]:
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
first_list = [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [32]:
first_array = np.array(first_list)

In [33]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
second_list = [1,2,3,-1.23,50,128000.56,4.56]

In [35]:
second_array = np.array(second_list)

In [36]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [37]:
third_list = ['akshay',18]
third_array = np.array(third_list)

In [38]:
third_array

array(['akshay', '18'], dtype='<U11')

In [39]:
third_array.dtype

dtype('<U11')

In [40]:
first_tuple =(5,10,15,20,25)
tuple_array = np.array(first_tuple)
tuple_array

array([ 5, 10, 15, 20, 25])

In [41]:
tuple_array.dtype

dtype('int32')

In [42]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
inter_arr = np.arange(100,130)
inter_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [44]:
int_arr = np.arange(100,151,2)
int_arr

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [45]:
fir_float = np.linspace(10,20)
fir_float

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [46]:
first_rand_arr = np.random.rand(10)

In [47]:
first_rand_arr

array([0.59735333, 0.01391464, 0.20090967, 0.28476398, 0.27209951,
       0.50276303, 0.99845645, 0.18990111, 0.10678251, 0.8164214 ])

In [48]:
first_z_array = np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [49]:
sec_arr = np.zeros((4,5))

In [50]:
sec_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
first_fill_array = np.empty(10,dtype = int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [52]:
first_full_array = np.full((4,5),8)
first_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [53]:
second_full_array = np.full(4,5)
second_full_array

array([5, 5, 5, 5])

In [55]:
fir_arr = np.arange(20)
fir_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
sec_arr = np.linspace((1,2),(10,20),10)
sec_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [75]:
third_arr = np.full((3,3,5),10)
third_arr

array([[[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]])

In [77]:
np.shape(fir_arr)

(20,)

In [78]:
np.shape(sec_arr)

(10, 2)

In [79]:
np.shape(third_arr)

(3, 3, 5)

In [80]:
np.size(fir_arr)

20

In [81]:
np.size(sec_arr)

20

In [82]:
np.size(third_arr)

45

In [83]:
fir_arr = np.array([1,2,3,5])
new= np.insert(fir_arr,3,4)
new

array([1, 2, 3, 4, 5])

In [84]:
sec_arr = np.array([1,2,3,4,5])
sec=np.append(sec_arr,6)
sec

array([1, 2, 3, 4, 5, 6])

In [86]:
dele=np.delete(sec,5)
dele

array([1, 2, 3, 4, 5])

In [87]:
inte=np.random.randint(0,20,20)
print(np.sort(inte))

[ 0  0  1  4  7  8  9  9  9 11 11 11 15 16 16 16 16 17 17 19]


In [95]:
tdim = np.array([[3, 2, 5, 7, 4], [5, 0, 8, 3, 1]])
tdim
print(np.sort(tdim))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [121]:
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
second_arr=np.reshape(first_arr,(3,4))

second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
third_arr=np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])